<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Page Remove="Resources\Styles.xaml" />
    <Page Remove="Resources\Templates.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\Windows\MainWindow.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Api\TaskApi\NewFolder\" />
    <Folder Include="Services\Api\TaskApi\Speed\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Styles.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Templates.xaml" />
  </ItemGroup>

</Project>
