<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Icons\image-pdf.png" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="Resources\Styles.xaml" />
    <Page Remove="Resources\Templates.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\Windows\MainWindow.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Api\TaskApi\NewFolder\" />
    <Folder Include="Services\Api\TaskApi\Speed\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiveCharts.Core" Version="0.9.8" />
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
    <PackageReference Include="MahApps.Metro.IconPacks" Version="6.2.1" />
    <PackageReference Include="QuestPDF" Version="2025.12.1" />
    <PackageReference Include="SharpVectors" Version="1.8.5" />
    <PackageReference Include="SharpVectors.Wpf" Version="1.8.5" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="SkiaSharp.Views.WPF" Version="3.119.1" />
    <PackageReference Include="WPF.UI" Version="3.4.2.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\backend\NetworkMonitor.Core\NetworkMonitor.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Icons\image-pdf.png" />
    <Resource Include="Resources\Styles.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Templates.xaml" />
  </ItemGroup>

</Project>
